[package]
name = "ginkgo-shell-language"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"
description = "The no_std GinkgoOS shell language parser and bytecode interpreter"

[lib]
path = "src/lib.rs"

[dependencies]
pest = { version = "=2.8.7", default-features = false }
pest_derive = { version = "=2.8.7", default-features = false }
